server:
  port: 8765

spring:
  application:
    name: gateWay
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8080/
          predicates:
            - Path=/tasks/**
