server:
  port: 8080

spring:
  application:
    name: gateWay
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8081/
          predicates:
            - Path=/tasks/**
